language: node_js
sudo: required
node: 
matrix:
  include:
  - os: osx
  - os: linux
node_js:
- '7'
before_install:
- openssl aes-256-cbc -K $encrypted_70968d214000_key -iv $encrypted_70968d214000_iv
  -in Certificates.p12.enc -out Certificates.p12 -d
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --no-install-recommends
  -y icnsutils graphicsmagick xz-utils; fi
addons:
  apt:
    packages:
    - xvfb
before_script:
- node --version
- npm install
- npm install -g electron
- node --version
- npm run package-ci
cache:
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"
install:
- nvm install 7
- export DISPLAY=':99.0'
- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
dist: trusty
env:
  matrix:
  # CSC_KEY_PASSWORD
  - secure: fhjSy8kPyKZF1GTygHYa6pE/AaM0GkZxk33AlJxyhPjpHr2q/ZCv32Cbx+m3NVp+UnMg0gZvpNkLlemio3427NboOOClrFsfn4j8tKyRN3cj7w7Ik+xqCRP+ZDGzJiSy7L+V+/OUgC5BPZZ/bbdhlZak42nN5iYuyTth/M06FatNKK3KVZyz9LG5AsE+tMfLqQxMMRJkAoG4oJw3bi+Y8tIaDNZmAy3I0X6RRfMLoi9e50+zonQ9JiTuI6gnAwQFld3QmRg6WJKIzGg/JbjVzzJaXe1f3b3x3rhtAK4nq3DEcTLE/9B9OKx20N6nboB437m9Pz8/3Qrcy/u/17pz49TVuWQGASCbvauneGJVKsezW7OJerLhLRH5n3RSLZPRjnvVZBd6SDAQC8fKSzYvr4PuDtaqww6AWjExUhlP2VQwwkoAxlFtAp0e0RSD+w7elZxLtqdKTJNQJ6pt/eE/Py+SPNIgpIERCtdKiQu2BZxP9688JS0a57quCoOteFT9k7mGURUTUjWh56ijfSh0ANP4v5GrhZC7F9skxW+brUlt2SKzAVVXBuYBxTGKO0U64zuk6/jbaTmAWM1lhv7TtNzMNHIWSU4jOnL6NgPJKVZoRC+1cO4C0AtI+6qIiye5W7uEjcaumKuS/cmG03aS7AoMFm1tEH/bMX/lw9JMiMA=
  
  # GH_TOKEN
  - secure: 1lgRLCzRfAaBMsbE/hEptrDbclmG7vjWpJSAKw54tvllsUi1VynvAf+dT0GTO8UzlMFj3yYxRpSvRIb1108frDZZfmKsifrLRGZNanegvDBox5Hp7lszhyv7V0CJsuuqo0RNYrZx1AS0HbiimJfFw1uH98xzcFZjOTeB6bfYoevkYdTaFgfgL1GGjVBUE1dg/8S4f90ShMYAE9DTktoC23AQy4gQ8eOWQydVEf3D21oASo6Z9KKfRFU7d6gd+rJV6Z5h+WJcGfDM4pjq/+ZwSnYz0A5fgkMXUb5DQ+2V++5bu7wO34VkLXrWwKITGURpIgWSduEMDLa4+NC4kTMDGV4HwHl3Fz6QWP8J5YLGKcaVp17kh6YEcXJUUKG+DMYrs221VwprW3Gd1OJLDO2jkT3zTqnqBPakXfqM2FGlN7WaRo/DAE74Iej1TmXnazsMrveg8pVjOiHGEM+Glhy0E/JEbcDY5sQa0fsQSZmo8RUWMNetMx/HIKtKcEO5J/+ffi2Sbq7+tGXAbCwIjRq0Qb+lIqsNCsR4kU4AFCKL06IhuB5rIRs2Ad33CluJdZTx6PlSmU+yfpXWVdTCj3Mq40IKkirSZDwG2EuT7WuzdDVxCOQXoaBl2Glx3frLTByyTgQuAHDntsa3hniqHFOFVsXvARKUKJRbE3w+fRTM0uQ=
  
  # CSC_LINK
  - secure: doeCl8c2Jta41qyMQwvuMPBo6XNhJuBkClvER68UTvJLG54Zo3VH+7d21KmVIb3ES2UmYmTvHM/S4Q8D9Q18OPQG9Sq/vuEn2kMr1/59eKV6JUEEjvypLAp9cRaTzmhZt0PIyVV/xFkcUEJcki3/SD8l8ywZBF/9nFaGVyZi9g3TbOYKmknmnY3QsBAITIgUrMK0Rr84/mMk5zoQXVx0SuPYloh4SGSWC/mfWQR8a6K3nxxr8zsw25H5+tZe5lEg2qkokkDL/aNmBWCen4KTlmgkOO+8W/Zw7gIF+BrhUtYllaXiQtu7WfRgnOVzLB9WpYMZf0W0KKAWjAJrdQZca+k8vKjQRHJFhxKtCjquRFC3TLwf9mYugkeobk5mvhahrLZeQl1PYRYP/C2jDYoEDi13VSV7P3maeAnl0TraUyaScx8of8iWLWtakcu2ozzS1fkmQy2x6dijs8+QQX2xmuO09GZGhDJDdezon1RrqgGFlefaOdP4Y3RCTA9CrDUYRUsvzy1/sRpCz1LWTc1o3K9iyHK9V8pg2NtHTR5//ZAAaIazZrUscFAXxEVd8slS3cobEZa+nYr+PHPb69TN+IvxUsGrP9vE4gmkSgk0SRTnovWBYrRNWCPa4ic/FeqYt+X9Vps7EYTePBWlGLIzF5z1Db0OZQ22NokphRsv+i0=
